# apiVersion: apps/v1
# kind:  DaemonSet
# metadata: 
#   name: daemonset
#   labels:
#     app: cwagentapp
# spec:
#     selector: 
#       matchLabels: 
#           app: cwagentapp
#     replicas: 4
#     template:
#       metadata:
#         labels:
#           name: cwagent
#           app: cwagentapp
#       spec:
#         containers:
#           - name: cwatch
#             image: amazon/cloudwatch-agent:latest
#             resources: 
#                 requests:
#                   cpu: "100m"
#                   memory: "128Mi
#             ports:
#                 - containerPort: 80
#                   protocol: TCP    

apiVersion: apps/v1
kind:  DaemonSet
metadata: 
  name: daemon
  labels:
    app: depapp
spec:
    selector: 
      matchLabels: 
          app: depapp
    template:
      metadata:
        labels:
          name: cwatch
          app: depapp
      spec:
        containers:
          - name: cwatch
            image: amazon/cloudwatch-agent:latest
            resources: 
                requests:
                  cpu: "100m"
                  memory: "128Mi
            ports:
                - containerPort: 80
                  protocol: TCP