apiVersion:  apps/v1  
kind:   StatefulSet
metadata: 
      name: statefulset
      labels:
          app: statefullapp
      spec:
          replica: 4
          selector:
            matachlabels:
              app: statefullapp
      template:
        metadata: 
          labels:
              name: new-statefullapp
              app:  statefullapp #replicasetapp1 change when using NotIn exp
        spec:
            containers: 
                - name: mysql 
                  image: mysql:latest
                  resources: 
                    requests:
                      cpu: "100m"
                      memory: "128Mi" 
                  ports: 
                      - containerPort: 3306
                        name: http
                        protocol: TCP
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: "1234"