apiVersion: v1 
kind: Service
metadata:
        name: nodeport1  #cluster 
spec:
    selector:
          app: mypod  
    type: NodePort
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx