
apiVersion: v1 
kind: Pod
metadata:
     labels:
      app: nginx
spec: 
  containers:
    - name: nginx 
      protocol: TCP
      image: nginx:latest 
      ports: 
       - containerPort: 80

---
apiVersion: v1
kind: Service 
metadata:
 name: service1
spec:
  selector: 
    app: nginx 
  type: NodePort
  ports: 
    - port: 80 
      targetPort: 80
...
