apiVersion: v1
kind: ReplicationController
metadata:
  name: rpc
  labels:
    apps: myapp
spec:
    replica: 3
    template:
      metadata: 
        label: 
          app: myapp1
      spec:
        containers:
          - name: nginx
            image: nginx:latest
            ports:
            - containerPort: 80
              protocol: TCP
          - name: tomcat
            image: tomcat:latest
            ports:
            - containerPort: 8080
              protocol: TCP
    selector: 
      app: myapp1