apiVersion: apps/v1
kind: ReplicaSet
metadata: 
 name: replicaset
 labels: 
    myapp: app1
spec:
  replicas: 3
  template:
    metadata: 
      name: nginxtest
      labels:
        myapp1: xyzapp
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
           - containerPort: 80
             protocol: TCP 
    metadata:
          name: my-service
          label: 
            srvapp: app3
          spec:
            type: NodePort
            selector:  
                app: my-pod
              #app.kubernetes.io/name: MyApp
          ports:
            - protocol: TCP
              name: nginx
              port: 80
              targetPort: 80
            - protocol: TCP
              name: tomcat
              port: 8080
              targetPort: 8080
  selector: 
    matchExpressions:
      - {key: myapp1, operator: In, values: [xyzapp]}  
        {key: srvapp, operator: In, values: [app3]}  