apiVersion: apps/v1
kind: DaemonSet
metadata: 
        name: daemoncloudwatchagent
        label:
            app: daemoncloudwatchagent
spec:
    replicas: 3  #specify number of pod's replica to be created. 
    template:
          #write here your pod's script from metadata and spec.
      metadata:
        name: 
        labels:
            app: daemoncloudwatchagent
      spec:
          containers:
              - name: daemoncloudwatchagent
                image: amazon/cloudwatch-agent:latest
                resources:
                    requests:
                        cpu: "10m"
                        memory: "12Mi" 
                ports:
                    - protocol: TCP
                      containerPort: 80
                      name: http  
    selector: 
        # matchExpressions:
        #   - {key: app, operator: In, values: [replicaset1 , replicaset2]}  
        # matchLabels:
        #         app: replicaset4     
        matchLabels:
            app: daemoncloudwatchagent  