apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pvol
spec:
  capacity:
          storage: 10G
  volume:  filesystem
  acessModes:
            -ReadWriteOnce
  persistenceVolumeReclainPolicy: Recycle
  storageClassName: standard
  hostPath:
      path: /mnt/data
